<div class="welcome">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <img src="./assets/img/banner/under-construction-banner.png" alt="Indian Food">
                <h1 class="text-uppercase mt-3 mb-0">
                    Comming Soon
                </h1>
                <p class="lead text-uppercase mb-2">
                    OUR WEBSITE IS BEING CONSTRUCTED BY<br>
                </p>
                <p>
                    Rahat Rayhan (Lead Developer)
                </p>
                <p>
                    Mohammed Noman (Project Manager)
                </p>
                <p>
                    Md. Shariful Islam (Designer)
                </p>
                <p>
                    Powered by CloudServer Inc (System Admin)
                </p>
                <p>
                    Follow us for update
                </P>

            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul class="nav-bottom">
                    <li>
                        <a href="https://github.com/rahatray/indianfood" target="_blank">
                            <i class="fab fa-github"></i>
                            Github
                    </a>
                    </li>
                    <li>
                        <a href="https://facebook.com/mdnoman2002" target="_blank">
                            <i class="fab fa-facebook"></i>
                            FaceBook
                    </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>